'use client'

import Link from 'next/link'

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <div className="bg-gradient-to-br from-teal-50 to-white border-b border-gray-200">
        <div className="max-w-2xl mx-auto px-4 py-12">
          <Link href="/" className="text-teal-600 hover:text-teal-700 text-sm font-medium mb-4 inline-block">
            ← Back to Harbor
          </Link>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Privacy Policy</h1>
          <p className="text-gray-600">Effective date: March 2026</p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-2xl mx-auto px-4 py-12">
        <div className="prose prose-sm max-w-none space-y-6 text-gray-700">
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">1. Overview</h2>
            <p>
              Harbor ("we", "us", "our", or "Company") operates the Harbor AI receptionist platform. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our service.
            </p>
            <p>
              Please read this Privacy Policy carefully. If you do not agree with our policies and practices, please do not use our service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">2. Information We Collect</h2>
            <p>We collect information in the following ways:</p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li><strong>Practice Information:</strong> Practice name, therapist name, location, specialties, insurance accepted, office hours</li>
              <li><strong>Contact Information:</strong> Email address, phone number for your practice</li>
              <li><strong>Call Data:</strong> Phone numbers of callers, call duration, transcripts of calls, summaries generated by our AI</li>
              <li><strong>Patient Information:</strong> Patient phone numbers, appointment information, crisis indicators from calls</li>
              <li><strong>Intake Screenings:</strong> PHQ-2 and GAD-2 scores collected during calls</li>
              <li><strong>Billing Information:</strong> Stripe customer ID and subscription status (not credit card details)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">3. How We Use Your Information</h2>
            <p>We use the information we collect for the following purposes:</p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>Providing and maintaining the Harbor AI receptionist service</li>
              <li>Generating call summaries and sending them to your practice email</li>
              <li>Tracking crisis indicators and alerting you when detected</li>
              <li>Managing your subscription and billing</li>
              <li>Improving and optimizing our service through AI model updates</li>
              <li>Communicating with you about your account or service updates</li>
              <li>Complying with legal obligations</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">4. Data Retention</h2>
            <p>
              We retain call logs and transcripts for <strong>90 days</strong> by default. After 90 days, call data is automatically deleted unless you request an extended retention period.
            </p>
            <p>
              Your practice information (name, contact details, settings) is retained as long as your account is active. After account deletion, we retain data for 30 days to comply with legal requirements.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">5. HIPAA and Patient Privacy</h2>
            <p>
              Harbor is designed to help therapy practices comply with HIPAA. However, we recommend that each practice:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>Execute a Business Associate Agreement (BAA) with Harbor before using the service</li>
              <li>Ensure patients consent to calls being answered by AI</li>
              <li>Use secure patient phone numbers and avoid sharing PHI over phone</li>
              <li>Regularly review crisis alerts and call summaries for accuracy</li>
            </ul>
            <p className="mt-3">
              Please contact <a href="mailto:privacy@harbor.ai" className="text-teal-600 hover:underline">privacy@harbor.ai</a> to execute a BAA if your practice hasn't already.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">6. Data Sharing</h2>
            <p>
              We do <strong>not sell or trade</strong> your practice data or patient information. We may share data only in these circumstances:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li><strong>Service Providers:</strong> With third parties (Twilio, Google, Anthropic, Stripe) who help us operate Harbor. These are bound by confidentiality agreements.</li>
              <li><strong>Legal Requirements:</strong> If required by law, court order, or government request</li>
              <li><strong>Account Protection:</strong> If necessary to protect the safety, rights, and property of Harbor, our users, or the public</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">7. Security</h2>
            <p>
              We implement industry-standard security measures including encryption, secure authentication, and regular security audits. However, no method of transmission over the Internet is 100% secure. We cannot guarantee absolute security of your data.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">8. Your Rights</h2>
            <p>You have the right to:</p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li><strong>Access:</strong> Request a copy of all data we hold about your practice</li>
              <li><strong>Deletion:</strong> Request deletion of your account and associated data (subject to legal retention requirements)</li>
              <li><strong>Export:</strong> Export your data in a portable format</li>
              <li><strong>Correction:</strong> Correct inaccurate information about your practice</li>
            </ul>
            <p className="mt-3">
              To exercise these rights, contact <a href="mailto:privacy@harbor.ai" className="text-teal-600 hover:underline">privacy@harbor.ai</a>.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">9. Third-Party Links</h2>
            <p>
              Harbor may contain links to third-party websites. We are not responsible for the privacy practices of these external sites. Please review their privacy policies before providing any information.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">10. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy from time to time. We will notify you of material changes via email. Your continued use of Harbor after changes constitutes acceptance of the updated policy.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">11. Contact Us</h2>
            <p>
              If you have questions about this Privacy Policy or our privacy practices, please contact:
            </p>
            <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 mt-3">
              <p className="font-medium text-gray-900">Harbor Privacy Team</p>
              <p className="text-sm text-gray-600">Email: privacy@harbor.ai</p>
            </div>
          </section>
        </div>
      </div>
    </div>
  )
}

