'use client'

import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'

const PHQ9_QUESTIONS = [
  'Little interest or pleasure in doing things',
    'Feeling down, depressed, or hopeless',
      'Trouble falling or staying asleep, or sleeping too much',
        'Feeling tired or having little energy',
          'Poor appetite or overeating',
            'Feeling bad about yourself — or that you are a failure or have let yourself or your family down',
              'Trouble concentrating on things, such as reading the newspaper or watching television',
                'Moving or speaking so slowly that other people could have noticed. Or the opposite — being so fidgety or restless that you have been moving around a lot more than usual',
                  'Thoughts that you would be better off dead or of hurting yourself in some way',
                  ]

                  const GAD7_QUESTIONS = [
                    'Feeling nervous, anxious, or on edge',
                      'Not being able to stop or control worrying',
                        'Worrying too much about different things',
                          'Trouble relaxing',
                            'Being so restless that it is hard to sit still',
                              'Becoming easily annoyed or irritable',
                                'Feeling afraid as if something awful might happen',
                                ]

                                const FREQUENCY_OPTIONS = [
                                  { value: 0, label: 'Not at all' },
                                    { value: 1, label: 'Several days' },
                                      { value: 2, label: 'More than half the days' },
                                        { value: 3, label: 'Nearly every day' },
                                        ]

                                        export default function OutcomePage() {
                                          const params = useParams()
                                            const token = params.token as string
                                              const [loading, setLoading] = useState(true)
                                                const [assessment, setAssessment] = useState<any>(null)
                                                  const [error, setError] = useState('')
                                                    const [responses, setResponses] = useState<number[]>([])
                                                      const [submitting, setSubmitting] = useState(false)
                                                        const [done, setDone] = useState(false)

                                                          useEffect(() => {
                                                              fetch(`/api/outcomes/${token}`)
                                                                    .then(r => r.json())
                                                                          .then(data => {
                                                                                  if (data.error) setError(data.error)
                                                                                          else {
                                                                                                    setAssessment(data)
                                                                                                              const questions = data.assessment_type === 'phq9' ? PHQ9_QUESTIONS : GAD7_QUESTIONS
                                                                                                                        setResponses(new Array(questions.length).fill(-1))
                                                                                                                                }
                                                                                                                                        setLoading(false)
                                                                                                                                              })
                                                                                                                                                    .catch(() => { setError('Unable to load assessment'); setLoading(false) })
                                                                                                                                                      }, [token])
                                                                                                                                                      
                                                                                                                                                        const questions = assessment?.assessment_type === 'phq9' ? PHQ9_QUESTIONS : GAD7_QUESTIONS
                                                                                                                                                          const isComplete = responses.length > 0 && responses.every(r => r >= 0)
                                                                                                                                                            const answeredCount = responses.filter(r => r >= 0).length
                                                                                                                                                            
                                                                                                                                                              const handleSubmit = async () => {
                                                                                                                                                                  if (!isComplete) return
                                                                                                                                                                      setSubmitting(true)
                                                                                                                                                                          const res = await fetch(`/api/outcomes/${token}`, {
                                                                                                                                                                                method: 'POST',
                                                                                                                                                                                      headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                            body: JSON.stringify({ responses }),
                                                                                                                                                                                                })
                                                                                                                                                                                                    const data = await res.json()
                                                                                                                                                                                                        if (data.error) { setError(data.error); setSubmitting(false) }
                                                                                                                                                                                                            else setDone(true)
                                                                                                                                                                                                              }
                                                                                                                                                                                                              
                                                                                                                                                                                                                if (loading) return (
                                                                                                                                                                                                                    <div className="min-h-screen bg-slate-900 flex items-center justify-center">
                                                                                                                                                                                                                          <div className="text-teal-400">Loading assessment...</div>
                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                  if (error) return (
                                                                                                                                                                                                                                      <div className="min-h-screen bg-slate-900 flex items-center justify-center p-4">
                                                                                                                                                                                                                                            <div className="bg-slate-800 rounded-xl p-8 max-w-md text-center">
                                                                                                                                                                                                                                                    <div className="text-red-400 text-lg mb-2">Not Found</div>
                                                                                                                                                                                                                                                            <div className="text-slate-400 text-sm">{error}</div>
                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                          const assessmentName = assessment?.assessment_type === 'phq9' ? 'PHQ-9 Depression Screener' : 'GAD-7 Anxiety Screener'
                                                                                                                                                                                                                                                                            const progress = Math.round((answeredCount / questions.length) * 100)
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                  <div className="min-h-screen bg-slate-900 py-8 px-4">
                                                                                                                                                                                                                                                                                        <div className="max-w-2xl mx-auto">
                                                                                                                                                                                                                                                                                                <div className="text-center mb-6">
                                                                                                                                                                                                                                                                                                          <div className="w-12 h-12 bg-teal-600 rounded-xl flex items-center justify-center mx-auto mb-3">
                                                                                                                                                                                                                                                                                                                      <span className="text-white font-bold text-lg">H</span>
                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                          <h1 className="text-white text-xl font-bold">{assessment?.practice_name}</h1>
                                                                                                                                                                                                                                                                                                                                                    <p className="text-slate-400 text-sm mt-1">{assessmentName}</p>
                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                    {done ? (
                                                                                                                                                                                                                                                                                                                                                                              <div className="bg-slate-800 rounded-2xl p-8 text-center">
                                                                                                                                                                                                                                                                                                                                                                                          <div className="w-16 h-16 bg-teal-600 rounded-full flex items-center justify-center mx-auto mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                        <svg className="w-8 h-8 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                                                                                                                                                                                                                                                                                                                                                                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                                                                                                                                                                                                                                                                                                                                                                                                                                      </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2 className="text-white text-xl font-bold mb-2">Thank you!</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-slate-400 text-sm">Your responses have been recorded. Your therapist will review them before your next session.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex justify-between text-xs text-slate-400 mb-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span>{answeredCount} of {questions.length} answered</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span>{progress}%</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="w-full bg-slate-700 rounded-full h-1.5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="bg-teal-500 h-1.5 rounded-full transition-all" style={{ width: `${progress}%` }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="bg-slate-800 rounded-2xl p-4 mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-slate-400 text-sm">Over the <strong className="text-white">last 2 weeks</strong>, how often have you been bothered by the following problems?</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {questions.map((question, idx) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div key={idx} className={`bg-slate-800 rounded-xl p-4 transition-all ${responses[idx] >= 0 ? 'ring-1 ring-teal-600/40' : ''}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-white text-sm mb-3 leading-relaxed">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-teal-400 font-bold mr-2">{idx + 1}.</span>{question}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="grid grid-cols-2 gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {FREQUENCY_OPTIONS.map(opt => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  key={opt.value}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => setResponses(r => { const n = [...r]; n[idx] = opt.value; return n })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className={`px-3 py-2 rounded-lg text-sm text-left transition-colors ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            responses[idx] === opt.value
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ? 'bg-teal-600 text-white font-medium'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : 'bg-slate-700 text-slate-300 hover:bg-slate-600'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {opt.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {assessment?.assessment_type === 'phq9' && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-slate-500 text-xs mt-3 text-center">PHQ-9 © Pfizer Inc. Used with permission.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={handleSubmit}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              disabled={!isComplete || submitting}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="mt-6 w-full bg-teal-600 hover:bg-teal-700 disabled:opacity-40 disabled:cursor-not-allowed text-white py-3.5 rounded-xl font-medium text-sm transition-colors"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {submitting ? 'Submitting...' : isComplete ? 'Submit Assessment ✓' : `Answer all ${questions.length} questions to submit`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
